In [5]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("blacklisted_addresses.csv")

In [9]:
df

,wallet_address,hex_address,blacklisted_timestamp,blacklisted_utc,transaction_id,label
0,TLhouDRQGCVB6xLuao86ky5Ns8FyoStg4z,0x75bfdc53b18902c3ca06da533687064ed56a37e3,1792459092,2026-10-20 01:18:12,7773112d0c2c87dc70ca0578386fada735481657b62e72...,1
1,TP6jUy5qZedW2KZpJfFEEAbGVyD9kQXn6k,0x9005fdc812841e422a59fe2521bb313d8e9a082b,1792459092,2026-10-20 01:18:12,bb1c8b6fed80cf23b7648d36b562ebb0cee6756ed0ae16...,1
2,TJhpBRFXNSoFpe6ek2opbrGhU21e8eCxJu,0x5fcfd7a0d8229cad64c0af4fe0b7da1e6f85872b,1792459092,2026-10-20 01:18:12,c5b99ff65619660033431f5951c82422b01094cb2087cc...,1
3,TQ5eAJ9EsMswAEyZHxF7rcLMt2e5BLBN1Q,0x9ac9423641c56ecc7a451faab3acfe7140e96747,1792459092,2026-10-20 01:18:12,29c2a79688e84c5f760f39cea35a77d402bfbd8d6ab694...,1
4,TE7Yn2gGgvZpnPUaN5oFc9nzdzXAspc7k2,0x2d7456a5bdbc24496b14ec74e0feacd620d82e65,1792458954,2026-10-20 01:15:54,c5d0482fd8a4fa09745af421d3c24d0275714a4b924d73...,1
...,...,...,...,...,...,...
4973,TJcQkjTu4y1aDqUwLd7k7REYhW8BEXBJc3,0x5eca353027cc36d4b21a6206c2a97f5b1bccff12,1752306501,2025-07-12 07:48:21,9bc53fa2b24d49ca77aa4e5f8d36f1138e95a9405d6c37...,1
4974,TJb4ppxKMVaecQ5xJc3Jez3L3mogizsVMs,0x5e8927d3e23c71116cb5e0b3ea26fdeb0a795280,1752306498,2025-07-12 07:48:18,08e09f9ed97f42386b628ccf3866490d4152cf95b0b82f...,1
4975,TWMv2fzK9ebHM4rHvtwPRnYPrQy4Uxx7MT,0xdfadea46aedfb5c33fbdfb11ab236816a5e11bf7,1752306495,2025-07-12 07:48:15,a52033a4e71626c4d72d9471c9226cd91f5b35c2cf0c93...,1
4976,TKPrsjbVAjuWZaXT3wqvxizZmzn9NAJySu,0x6762bb0430a48a4f60e8b3f29fd34f0bdd0eed2a,1752306492,2025-07-12 07:48:12,036d4c2625e84ac60b47d80da2dfeba400a77e579187e8...,1
4977,TH8g7dUSxgvSpEKXcaSEaBVofJAuvCaxGc,0x4e9341d63912264943247608e35e1e2a50d2e77f,1752306489,2025-07-12 07:48:09,6eaa83b46181b2c43419a0c63305f1aa6ab24f2c00f6b8...,1

In [11]:
df.drop(columns=['label'], inplace=True)
df

,wallet_address,hex_address,blacklisted_timestamp,blacklisted_utc,transaction_id
0,TLhouDRQGCVB6xLuao86ky5Ns8FyoStg4z,0x75bfdc53b18902c3ca06da533687064ed56a37e3,1792459092,2026-10-20 01:18:12,7773112d0c2c87dc70ca0578386fada735481657b62e72...
1,TP6jUy5qZedW2KZpJfFEEAbGVyD9kQXn6k,0x9005fdc812841e422a59fe2521bb313d8e9a082b,1792459092,2026-10-20 01:18:12,bb1c8b6fed80cf23b7648d36b562ebb0cee6756ed0ae16...
2,TJhpBRFXNSoFpe6ek2opbrGhU21e8eCxJu,0x5fcfd7a0d8229cad64c0af4fe0b7da1e6f85872b,1792459092,2026-10-20 01:18:12,c5b99ff65619660033431f5951c82422b01094cb2087cc...
3,TQ5eAJ9EsMswAEyZHxF7rcLMt2e5BLBN1Q,0x9ac9423641c56ecc7a451faab3acfe7140e96747,1792459092,2026-10-20 01:18:12,29c2a79688e84c5f760f39cea35a77d402bfbd8d6ab694...
4,TE7Yn2gGgvZpnPUaN5oFc9nzdzXAspc7k2,0x2d7456a5bdbc24496b14ec74e0feacd620d82e65,1792458954,2026-10-20 01:15:54,c5d0482fd8a4fa09745af421d3c24d0275714a4b924d73...
...,...,...,...,...,...
4973,TJcQkjTu4y1aDqUwLd7k7REYhW8BEXBJc3,0x5eca353027cc36d4b21a6206c2a97f5b1bccff12,1752306501,2025-07-12 07:48:21,9bc53fa2b24d49ca77aa4e5f8d36f1138e95a9405d6c37...
4974,TJb4ppxKMVaecQ5xJc3Jez3L3mogizsVMs,0x5e8927d3e23c71116cb5e0b3ea26fdeb0a795280,1752306498,2025-07-12 07:48:18,08e09f9ed97f42386b628ccf3866490d4152cf95b0b82f...
4975,TWMv2fzK9ebHM4rHvtwPRnYPrQy4Uxx7MT,0xdfadea46aedfb5c33fbdfb11ab236816a5e11bf7,1752306495,2025-07-12 07:48:15,a52033a4e71626c4d72d9471c9226cd91f5b35c2cf0c93...
4976,TKPrsjbVAjuWZaXT3wqvxizZmzn9NAJySu,0x6762bb0430a48a4f60e8b3f29fd34f0bdd0eed2a,1752306492,2025-07-12 07:48:12,036d4c2625e84ac60b47d80da2dfeba400a77e579187e8...
4977,TH8g7dUSxgvSpEKXcaSEaBVofJAuvCaxGc,0x4e9341d63912264943247608e35e1e2a50d2e77f,1752306489,2025-07-12 07:48:09,6eaa83b46181b2c43419a0c63305f1aa6ab24f2c00f6b8...

In [13]:
df["wallet_address"]

0       TLhouDRQGCVB6xLuao86ky5Ns8FyoStg4z
1       TP6jUy5qZedW2KZpJfFEEAbGVyD9kQXn6k
2       TJhpBRFXNSoFpe6ek2opbrGhU21e8eCxJu
3       TQ5eAJ9EsMswAEyZHxF7rcLMt2e5BLBN1Q
4       TE7Yn2gGgvZpnPUaN5oFc9nzdzXAspc7k2
                       ...
4973    TJcQkjTu4y1aDqUwLd7k7REYhW8BEXBJc3
4974    TJb4ppxKMVaecQ5xJc3Jez3L3mogizsVMs
4975    TWMv2fzK9ebHM4rHvtwPRnYPrQy4Uxx7MT
4976    TKPrsjbVAjuWZaXT3wqvxizZmzn9NAJySu
4977    TH8g7dUSxgvSpEKXcaSEaBVofJAuvCaxGc
Name: wallet_address, Length: 4978, dtype: str

In [14]:
df.to_csv("blacklisted_addresses_cleaned.csv", index=False)